# Generated by Django 4.2.4 on 2023-08-15 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0002_alter_company_size_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('fila_name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 8, 15, 13, 22, 1, 313913, tzinfo=datetime.timezone.utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 8, 15, 13, 22, 1, 313937, tzinfo=datetime.timezone.utc))),
                ('total_rows', models.IntegerField()),
                ('process_rows', models.IntegerField()),
                ('status', models.CharField(default='In Progress', max_length=10)),
            ],
        ),
    ]
