# Generated by Django 4.2.4 on 2023-08-15 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0003_uploadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
