# Generated by Django 4.2.4 on 2023-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0005_rename_fila_name_uploadlog_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
